Updating readme
Crown-Commercial-Service/ccs-conclave-identifier-service pull request #95
Opened 2023-03-24 10:52 UTC by domducsutcliffe

- Updated the shields so that they link to the repo and are relevent to the dev work that's happening e.g. removed forks, stars & build tests 
- Removed the Road map as this hadn't been started. Potentially will add this as an issue because we could describe MVP 0,1,2 quite profitably here
- Added some details to the setup 
- Added dev contacts

2023-03-24 11:27 UTC, tberey approved these changes

2023-03-24 11:28 UTC, tberey requested changes
I would just change me from Senior Developer, to Lead Developer (I am not a senior technically)

2023-03-27 09:27 UTC, domducsutcliffe commented
@tberey comment addressed, please approve when ready !

2023-03-27 15:15 UTC, tberey approved these changes

2023-03-28 14:33 UTC, merged